AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Simple SAM template for a Lambda function using a Docker image, triggered by S3.

Resources:
  sabuhos3processuploadedfile:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command: ["lambda_function.lambda_handler"]
      # No ImageUri!
      MemorySize: 1024
      Timeout: 300
      Events:
        S3Upload:
          Type: S3
          Properties:
            Bucket: !Ref UploadBucket
            Events:
              - s3:ObjectCreated:*
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref UploadBucket
        - CloudWatchLogsPolicy: {}
      Environment:
        Variables:
          AWS_SAM_LOCAL: 'true'
          LOCAL_TEST_FILE: '/var/task/test.pdf'

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
